Importing Libraries

In [25]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [26]:
tf.__version__

'2.11.0'

Data Pre-Processing

Importing the dataset

In [27]:
data = pd.read_excel('energy.xlsx')
data.head()

AT      V       AP     RH      PE
0  14.96  41.76  1024.07  73.17  463.26
1  25.18  62.96  1020.04  59.08  444.37
2   5.11  39.40  1012.16  92.14  488.56
3  20.86  57.32  1010.24  76.64  446.48
4  10.82  37.50  1009.23  96.62  473.90

In [28]:
x = data.iloc[ : ,:-1].values
y = data.iloc[:, -1].values

In [29]:
print(x)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]


In [30]:
print(y)

[463.26 444.37 488.56 ... 429.57 435.74 453.28]


Splitting the dataset into training set and test set

In [31]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

Building the ANN

Initializing the ANN

ANN architecture can be of types (i) sequence of layers (ii)Computational graph 

In [32]:
ann = tf.keras.models.Sequential()

Adding the input layer and the first hidden layer

    -> Number of input layers need not be specified explicitly,  automatically recognised when the matrix of features are         loaded while training the model
    -> units = 6 denotes that there are 6 hidden layers

In [33]:
ann.add(
    tf.keras.layers.Dense(units = 6,  activation = 'relu')
)

Adding the Seconnd hidden layer

In [34]:
ann.add(
    tf.keras.layers.Dense(units = 6, activation = 'relu')
)

Adding the output layer

    ->  sigmoid : ANN binnary classification
    ->  softmax activation function : ANN multiple classification
    ->  no activation function : regression

In [35]:
ann.add(
    tf.keras.layers.Dense(units = 1)
)

Training the ANN

Compiling the ANN

In [36]:
ann.compile(
    optimizer = 'adam',
    loss = 'mean_squared_error'
)

Training the ANN model on the training set

In [37]:
ann.fit(X_train, y_train, batch_size = 32, epochs=100)

Epoch 1/100
240/240 [==============================] - 1s 1ms/step - loss: 34762.5547
Epoch 2/100
240/240 [==============================] - 0s 1ms/step - loss: 145.8416
Epoch 3/100
240/240 [==============================] - 0s 2ms/step - loss: 140.8699
Epoch 4/100
240/240 [==============================] - 0s 2ms/step - loss: 135.2225
Epoch 5/100
240/240 [==============================] - 0s 1ms/step - loss: 128.6916
Epoch 6/100
240/240 [==============================] - 0s 1ms/step - loss: 121.1744
Epoch 7/100
240/240 [==============================] - 0s 1ms/step - loss: 113.1301
Epoch 8/100
240/240 [==============================] - 0s 968us/step - loss: 104.7191
Epoch 9/100
240/240 [==============================] - 0s 1ms/step - loss: 95.9637
Epoch 10/100
240/240 [==============================] - 0s 1ms/step - loss: 86.9483
Epoch 11/100
240/240 [==============================] - 0s 1ms/step - loss: 78.4017
Epoch 12/100
240/240 [==============================] - 0s 1ms/step - los

Predicting the results of the test set

In [38]:
y_pred = ann.predict(X_test)

60/60 [==============================] - 0s 935us/step


In [39]:
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test),1)), 1))

[[430.84 431.23]
 [461.85 460.01]
 [465.34 461.14]
 ...
 [472.59 473.26]
 [439.37 438.  ]
 [458.59 463.28]]
